all:
    children:
        elk:
            hosts:
                elk.prod.***ARANGO_DB_NAME***.bio:
        webservers:
            hosts:
                demo.***ARANGO_DB_NAME***.bio:
                test.***ARANGO_DB_NAME***.bio:
                kg.***ARANGO_DB_NAME***.bio:
        demo:
            hosts:
                demo.***ARANGO_DB_NAME***.bio:
        staging:
            hosts:
                test.***ARANGO_DB_NAME***.bio:
        prod:
            hosts:
                kg.***ARANGO_DB_NAME***.bio:
