all:
    children:
        elk:
            hosts:
                35.238.72.201:
        webservers:
            hosts:
                35.223.19.98:
                34.67.176.248:
                35.225.4.84:
                34.69.0.24:
        qa:
            hosts:
                35.225.4.84:
        demo:
            hosts:
                35.223.19.98:
        staging:
            hosts:
                34.67.176.248:
        prod:
            hosts:
                34.69.0.24:
        traefik:
            hosts:
                35.239.196.222:
        nlptraining:
            hosts:
                34.122.15.118:
