$ANSIBLE_VAULT;1.1;AES256
38313162373266643939376363646437333430616532356662396230633737656463643065643565
6135636134343531396331376132613230636162333633650a356662383439663637646662663765
64396332316133313064396635666162343533626530626432663836316161343239636463303335
6635373632343634360a373964643534343337356636303430633166306266396164366633393934
63343766306362626132623132663836393736386330643661386232316130623534313736386138
38353235623838366432323262393265663036356338303164303132336362636132346235613936
34313662613166303666663262323962353934623933346334613632613231373762363638373563
64653338663436656637326535346530316534343735663264356532656439666238316666643738
64653764383238666533653133353731393638326562386535393463356339383132353861336331
38343237613966306661316133326335613830633361333930366465663736656637326265333964
31393230343364653139626235376366343235366639386534613364386166613965306338323465
34373566336264323561
